# Generated by Django 5.2.6 on 2025-09-12 14:00

from django.db import migrations
from django.utils.timezone import now

def create_default_admin(apps, schema_editor):
    User = apps.get_model('users', 'User')

    if not User.objects.filter(username='admin').exists():
        User.objects.create(
            username='admin',
            email='admin@example.com',
            password='123456',
            first_name='admin',
            role='admin',
            is_active=True,
            last_login=now(),
        )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_admin),
    ]
